In [42]:
#ZOBIA AHMED / 2022F-BSE-330 / LAB 05 / TASK 01:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
# Data from the table
data = {
    "Gender": ["male", "male", "male", "male", "female", "female", "female", "female"],
    "Height": [6.00, 5.92, 5.58, 5.92, 5.00, 5.50, 5.42, 5.75],
    "Weight": [180, 190, 170, 165, 100, 150, 130, 150],
    "Foot_Size": [12, 11, 12, 10, 6, 8, 7, 9]
}
# Creating a DataFrame
df = pd.DataFrame(data)
# Encoding the Gender column
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])
# Splitting the features and target
X = df[["Height", "Weight", "Foot_Size"]]
y = df["Gender"]
# Training the Decision Tree Classifier
clf = DecisionTreeClassifier()
clf.fit(X, y)
# Making predictions on the training data
y_pred = clf.predict(X)
print("ZOBIA AHMED / 2022F-BSE-330 / LAB 05 / TASK 01:\n")
# Calculating accuracy
accuracy = accuracy_score(y, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")
# Generating the confusion matrix
conf_matrix = confusion_matrix(y, y_pred)
print("Confusion Matrix:")
print(conf_matrix)
# Predicting for a predefined new entry
new_entry = pd.DataFrame([[5.80, 155, 9]], columns=["Height", "Weight", "Foot_Size"])  # Predefined values as DataFrame
prediction = clf.predict(new_entry)
predicted_gender = label_encoder.inverse_transform(prediction)[0]
print(f"Prediction for entry {new_entry.values.tolist()[0]}: The predicted gender is '{predicted_gender}'.")

ZOBIA AHMED / 2022F-BSE-330 / LAB 05 / TASK 01:

Model Accuracy: 1.00
Confusion Matrix:
[[4 0]
 [0 4]]
Prediction for entry [5.8, 155.0, 9.0]: The predicted gender is 'female'.


In [44]:
#ZOBIA AHMED / 2022F-BSE-330 / LAB 05 / TASK 02:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
# Data from the table
data = {
    "Gender": ["male", "male", "male", "male", "female", "female", "female", "female"],
    "Height": [6.10, 5.85, 5.65, 6.00, 5.25, 5.55, 5.35, 5.80],
    "Weight": [185, 195, 175, 160, 110, 140, 135, 145],
    "Foot_Size": [13, 11, 12, 10, 7, 8, 7, 9]
}
# Creating a DataFrame
df = pd.DataFrame(data)
# Encoding the Gender column
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])
# Splitting the features and target
X = df[["Height", "Weight", "Foot_Size"]]
y = df["Gender"]
# Training the Decision Tree Classifier
clf = DecisionTreeClassifier()
clf.fit(X, y)
# Making predictions on the training data
y_pred = clf.predict(X)
print("ZOBIA AHMED / 2022F-BSE-330 / LAB 05 / TASK 02:\n")
# New entry to predict and add to the dataset
new_entry = pd.DataFrame([[5, 165, 9]], columns=["Height", "Weight", "Foot_Size"])  # Predefined values as DataFrame
prediction = clf.predict(new_entry)
predicted_gender = label_encoder.inverse_transform(prediction)[0]
print(f"Prediction for entry {new_entry.values.tolist()[0]}: The predicted gender is '{predicted_gender}'.")
# Adding the new entry to the dataset
new_entry['Gender'] = label_encoder.transform([predicted_gender])  # Encode predicted gender
df = pd.concat([df, new_entry], ignore_index=True)
# Retraining the model with the updated dataset
X = df[["Height", "Weight", "Foot_Size"]]
y = df["Gender"]
clf.fit(X, y)
# Evaluating the updated model
y_pred_updated = clf.predict(X)
updated_accuracy = accuracy_score(y, y_pred_updated)
print(f"Updated Model Accuracy: {updated_accuracy:.2f}")
updated_conf_matrix = confusion_matrix(y, y_pred_updated)
print("Updated Confusion Matrix:")
print(updated_conf_matrix)

ZOBIA AHMED / 2022F-BSE-330 / LAB 05 / TASK 02:

Prediction for entry [5, 165, 9]: The predicted gender is 'female'.
Updated Model Accuracy: 1.00
Updated Confusion Matrix:
[[5 0]
 [0 4]]


In [48]:
#ZOBIA AHMED / 2022F-BSE-330 / LAB 05 / TASK 03:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
# Data from the table
data = [
    ["male", 6.00, 180, 12],
    ["male", 5.92, 190, 11],
    ["male", 5.58, 170, 12],
    ["male", 5.92, 165, 10],
    ["female", 5.00, 100, 6],
    ["female", 5.50, 150, 8],
    ["female", 5.42, 130, 7],
    ["female", 5.75, 150, 9]
]
# Converting the data into numpy arrays
data = np.array(data, dtype=object)
# Splitting features and target
X = data[:, 1:].astype(float)  # Features: Height, Weight, Foot_Size
y = data[:, 0]                 # Target: Gender
# Encoding the target (Gender)
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
# Training the Decision Tree Classifier
clf = DecisionTreeClassifier()
clf.fit(X, y_encoded)
# Making predictions on the training data
y_pred = clf.predict(X)
print("ZOBIA AHMED / 2022F-BSE-330 / LAB 05 / TASK 03:\n")
# New entry to predict and add to the dataset
new_entry = np.array([[4.8, 140, 7]])  # Predefined new entry (Height, Weight, Foot_Size)
prediction = clf.predict(new_entry)
predicted_gender = label_encoder.inverse_transform(prediction)[0]
print(f"Prediction for entry {new_entry.tolist()[0]}: The predicted gender is '{predicted_gender}'.")
# Adding the new entry to the dataset
X = np.vstack([X, new_entry])  # Adding new entry to features
y_encoded = np.append(y_encoded, label_encoder.transform([predicted_gender]))  # Adding predicted gender to target
# Retraining the model with the updated dataset
clf.fit(X, y_encoded)
# Evaluating the updated model
y_pred_updated = clf.predict(X)
updated_accuracy = accuracy_score(y_encoded, y_pred_updated)
print(f"Updated Model Accuracy: {updated_accuracy:.2f}")
updated_conf_matrix = confusion_matrix(y_encoded, y_pred_updated)
print("Updated Confusion Matrix:")
print(updated_conf_matrix)

ZOBIA AHMED / 2022F-BSE-330 / LAB 05 / TASK 03:

Prediction for entry [4.8, 140.0, 7.0]: The predicted gender is 'female'.
Updated Model Accuracy: 1.00
Updated Confusion Matrix:
[[5 0]
 [0 4]]


In [54]:
#ZOBIA AHMED / 2022F-BSE-330 / LAB 05 / HOMETASK:
# Importing necessary libraries
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
# Load the dataset
df = pd.read_csv("patient_data_zobia.csv")
# Encoding categorical variables
df['Family History'] = df['Family History'].map({'No': 0, 'Yes': 1})
df['Diet Type'] = df['Diet Type'].map({'Balanced': 0, 'High Sugar': 1, 'Low Carb': 2})
df['Category'] = df['Category'].map({'Healthy': 0, 'Pre-Diabetic': 1, 'Diabetic': 2})
# Splitting the data into training and testing sets (first 30 for training, last 10 for testing)
train_data = df.iloc[:30]
test_data = df.iloc[30:]
# Separate features and target variable
X_train = train_data.drop(['Patient ID', 'Category'], axis=1)
y_train = train_data['Category']
X_test = test_data.drop(['Patient ID', 'Category'], axis=1)
y_test = test_data['Category']
# Train the Decision Tree model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
# Predict on the test set
y_pred = model.predict(X_test)
# Add the predicted values to the test data
test_data_with_predictions = test_data.copy()
test_data_with_predictions['Predicted Category'] = y_pred
print("ZOBIA AHMED / 2022F-BSE-330 / LAB 05 / HOMETASK:\n")
# Display the full test data with actual and predicted values
print("(1): Test Data Of Last 10 Rows With Predictions:")
print(test_data_with_predictions)
# Calculate accuracy and confusion matrix
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print("\n(2): Accuracy of the model:", accuracy)
print("(3): Confusion Matrix:\n", conf_matrix)

ZOBIA AHMED / 2022F-BSE-330 / LAB 05 / HOMETASK:

(1): Test Data Of Last 10 Rows With Predictions:
    Patient ID  Age  BMI  Blood Pressure  Glucose Level  \
30         131   62   33             145            165   
31         132   49   27             128            105   
32         133   41   29             132             95   
33         134   56   28             137            130   
34         135   35   25             126             90   
35         136   57   32             139            145   
36         137   48   30             136            110   
37         138   52   31             141            120   
38         139   44   27             133            105   
39         140   60   34             147            170   

    Physical Activity Level  Family History  Diet Type  Category  \
30                      1.0               1          1         2   
31                      2.3               0          0         1   
32                      4.0               0    